[package]
name = "leet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "leetlib"
path = "src/lib/leetlib.rs"

[[bin]]
name = "leetbin"
path = "src/bin/leetbin.rs"

[dependencies]
